import Head from "next/head";
import Carousel from "react-multi-carousel";
import { LeftArrow, RightArrow } from "../components/Arrow";
import BlogCard from "../components/home/BlogCard";
import FeaturedCard from "../components/home/FeaturedCard";
import WidgetPost from "../components/WidgetPost";
import getPosts from "../services/posts";
import responsive from "../utils/carouselResConfig";

export const getStaticProps = async () => {
  try {
    const { posts } = await getPosts();
    return { props: { blogs: posts } };
  } catch (error) {
    console.log(error);
  }
};

const Home = ({ blogs }) => {
  return (
    <>
      <Head>
        <title>Web Stories || We tell it right</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto laptop:px-5 mobile:px-3 pt-10 pb-5">
        <Carousel
          responsive={responsive}
          infinite
          customLeftArrow={LeftArrow}
          customRightArrow={RightArrow}
          itemClass="px-4"
        >
          <FeaturedCard />
          <FeaturedCard />
          <FeaturedCard />
          <FeaturedCard />
          <FeaturedCard />
          <FeaturedCard />
        </Carousel>
      </section>

      <section className="container mx-auto laptop:px-5 mobile:px-3 grid grid-cols-3 py-10">
        <div className="col-span-2 tablet:col-span-3 space-y-7 px-14 laptop:px-0">
          {blogs.map((blog) => (
            <BlogCard key={blog.id} blog={blog} />
          ))}
        </div>
        <aside className="col-span-1">
          <div className="sticky top-20 space-y-5">
            <div className="space-y-3">
              <h2 className="text-xl text-white font-semibold">Top Post:</h2>
              <WidgetPost />
              <WidgetPost />
              <WidgetPost />
            </div>
            <div className="space-y-3">
              <h2 className="text-xl text-white font-semibold">Category:</h2>
              <WidgetPost />
              <WidgetPost />
              <WidgetPost />
            </div>
          </div>
        </aside>
      </section>
    </>
  );
};

export default Home;
