import Head from "next/head";
import Carousel from "react-multi-carousel";
import BlogCard from "../components/home/BlogCard";
import { getPosts } from "../services/posts";

const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 3000 },
    items: 5,
  },
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 3,
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};

export default function Home({ blogs }) {
  // const { loading, error, data } = useQuery(getPosts);

  return (
    <>
      <Head>
        <title>Web Stories || We tell it right</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel responsive={responsive} className="h-52">
        <div>
          {/* <Image
            src="/DrKQPF0/images-q-tbn-ANd9-Gc-Rz19vs-WTF44r453-MYR8qg-Uu-VJyaapu5kkxng-usqp-CAU.jpg"
            layout="fill"
            alt=""
          /> */}
        </div>
        <div>Item 2</div>
        <div>Item 3</div>
        <div>Item 4</div>
      </Carousel>

      <div className="container mx-auto laptop:px-5 mobile:px-3 grid grid-cols-3 my-10">
        <div className="col-span-2 tablet:col-span-3 space-y-7 px-14 laptop:px-0">
          {blogs.map((blog) => (
            <BlogCard key={blog.id} blog={blog} />
          ))}
        </div>
        <div className="sticky top-0">
          <h2>This is side bar</h2>
        </div>
      </div>
      <div className="h-72 border"></div>
    </>
  );
}

export const getStaticProps = async () => {
  try {
    const { posts } = await getPosts();
    return { props: { blogs: posts } };
  } catch (error) {
    console.log(error);
  }
};
