import parse from "html-react-parser";
import moment from "moment";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import AuthorCard from "../../components/details/AuthorCard";
import CommentCard from "../../components/details/CommentCard";
import CommentForm from "../../components/details/CommentForm";
import WidgetCard from "../../components/WidgetCard";
import getComments from "../../services/getComments";
import getRelatedStories from "../../services/getRelatedSories";
import getStories from "../../services/getStories";
import getStory from "../../services/getStory";
import styles from "../../styles/story.module.css";

export const getStaticPaths = async () => {
  const { posts } = await getStories();
  return {
    paths: posts.map(({ slug }) => ({ params: { slug } })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const { slug } = params;
  const { post } = await getStory(slug);
  const categories = JSON.stringify(post.categories.map(({ slug }) => slug));

  const { posts } = await getRelatedStories({ slug, categories });
  const { comments } = await getComments(slug);

  return { props: { post, related: posts, comments } };
};

const Details = ({ post, related, comments }) => {
  const { title, featuredImage, author, createdAt, content } = post;

  return (
    <>
      <Head>
        <title>Web Stories || {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto laptop:px-5 mobile:px-3 grid grid-cols-3 py-5 gap-5">
        <div className="col-span-2 tablet:col-span-3">
          <div className="bg-white p-5 rounded-lg space-y-3">
            <figure className="space-y-3">
              <figcaption className="text-4xl font-semibold inline-flex gap-4">
                <span className="text-5xl text-[#6B58FA]">➦</span>
                <span>{title}</span>
              </figcaption>
              <div className="relative w-full h-96 mobile:h-60 rounded-md overflow-hidden">
                <Image src={featuredImage.url} alt={title} layout="fill" />
              </div>
            </figure>

            <div className="flex justify-between items-center">
              <div className="flex items-center gap-1">
                <div className="h-9 w-9 rounded-full overflow-hidden relative">
                  <Image src={author.avatar.url} alt={author.name} layout="fill" />
                </div>
                <p className="text-lg font-semibold">{author.name}</p>
              </div>

              <div className="flex items-center gap-1">
                <label className="text-2xl">📅</label>
                <time className="text-base">{moment(createdAt).format("ll")}</time>
              </div>
            </div>

            <div className={styles.story_details}>{parse(content.html)}</div>
          </div>

          <div className="relative pt-14 tablet:mt-5">
            <AuthorCard author={author} />
          </div>

          <div className="bg-white p-5 rounded-lg mt-10 space-y-3">
            <h2 className="text-2xl font-semibold">Discussion ({comments.length})</h2>
            {comments.map((item, key) => (
              <CommentCard key={key} data={item} />
            ))}
            <CommentForm />
          </div>
        </div>
        <aside className="col-span-1 tablet:col-span-3">
          <div className="sticky top-20 space-y-5">
            <div className="space-y-3 tablet:mt-5">
              <h2 className="text-xl text-white font-semibold">Related Story:</h2>
              {related.map((i, key) => (
                <WidgetCard key={key} widget={i} />
              ))}
            </div>
          </div>
        </aside>
      </section>
    </>
  );
};

export default Details;
